### ISSUE TITLE
I don't like you're tone

### ISSUE THREAD

**Issue by DapperZoid** [coshiro1/self-checkout-speedrun#4]
ok

_Originally posted by @coshiro1 in https://github.com/coshiro1/self-checkout-speedrun/issues/3#issuecomment-853429130_

**Comment by coshiro1** [comment]
> ok
> 
> _Originally posted by @coshiro1 in [#3 (comment)](https://github.com/coshiro1/self-checkout-speedrun/issues/3#issuecomment-853429130)_

OK 🤮
